Copy entire contents of lib/ when building pkgs or installing
The yaml3 library was never included in the packages or installed when
doing 'make install'. This caused errors on Python v3 such as:

ModuleNotFoundError: No module named 'yaml3'